apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omega-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: omegaempleos.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 8000
