name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-backend, deploy-frontend]
  workflow_dispatch:

jobs:
  deploy-backend:
    if: github.event.action == 'deploy-backend' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar acceso a Kubernetes en el VPS
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Aplicar PostgreSQL en Kubernetes
        run: |
          kubectl apply -f deploy/postgres-deployment.yaml

      - name: Esperar a que PostgreSQL esté listo
        run: |
          echo "Esperando 10s para que PostgreSQL se inicie..."
          sleep 10
          kubectl wait --for=condition=ready pod -l app=postgres --timeout=90s

      - name: Eliminar `Job` de Alembic si existe
        run: |
          kubectl delete job alembic-migration --ignore-not-found=true

      - name: Ejecutar migraciones con Alembic
        run: |
          kubectl apply -f deploy/alembic-job.yaml

      - name: Esperar a que el Job de Alembic termine
        run: |
          kubectl wait --for=condition=complete job/alembic-migration --timeout=120s

      - name: Aplicar Backend en Kubernetes
        run: |
          kubectl apply -f deploy/backend-deployment.yaml

      - name: Eliminar el Pod de Backend para forzar el redeploy
        run: |
          kubectl delete pod -l app=fastapi --ignore-not-found=true

      - name: Verificar los Pods
        run: |
          kubectl get pods -A

  deploy-frontend:
    if: github.event.action == 'deploy-frontend' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar acceso a Kubernetes en el VPS
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Aplicar Frontend en Kubernetes
        run: |
          kubectl apply -f deploy/frontend-deployment.yaml

      - name: Eliminar el Pod de Frontend para forzar el redeploy
        run: |
          kubectl delete pod -l app=frontend --ignore-not-found=true

      - name: Verificar los Pods
        run: |
          kubectl get pods -A
